[workspace]
resolver = "2"

members = [
    "bevy-strolle",
    "strolle",
    "strolle-gpu",
    "strolle-shader-builder",
    "strolle-shaders/atmosphere",
    "strolle-shaders/direct-denoising",
    "strolle-shaders/direct-initial-shading",
    "strolle-shaders/direct-raster",
    "strolle-shaders/direct-resolving",
    "strolle-shaders/direct-spatial-resampling",
    "strolle-shaders/direct-temporal-resampling",
    "strolle-shaders/direct-tracing",
    "strolle-shaders/indirect-denoising",
    "strolle-shaders/indirect-initial-shading",
    "strolle-shaders/indirect-initial-tracing",
    "strolle-shaders/indirect-resolving",
    "strolle-shaders/indirect-spatial-resampling",
    "strolle-shaders/indirect-temporal-resampling",
    "strolle-shaders/output-drawing",
    "strolle-shaders/reprojection",
    "strolle-utils/noise-visualizer",
    "strolle-utils/sandbox",
]

# TODO https://github.com/gfx-rs/naga/issues/2373
[patch."crates-io"]
naga = { git = "https://github.com/Patryk27/naga", branch = "strolle" }
