[workspace]
resolver = "2"

members = [
    "strolle",
    "strolle-gpu",
    "strolle-shader-builder",
    "strolle-shaders/atmosphere",
    "strolle-shaders/bvh-heatmap",
    "strolle-shaders/direct-denoising",
    "strolle-shaders/direct-raster",
    "strolle-shaders/direct-resolving",
    "strolle-shaders/direct-shading",
    "strolle-shaders/direct-spatial-resampling",
    "strolle-shaders/direct-temporal-resampling",
    "strolle-shaders/frame-composition",
    "strolle-shaders/frame-reprojection",
    "strolle-shaders/indirect-diffuse-denoising",
    "strolle-shaders/indirect-diffuse-resolving",
    "strolle-shaders/indirect-diffuse-spatial-resampling",
    "strolle-shaders/indirect-diffuse-temporal-resampling",
    "strolle-shaders/indirect-shading",
    "strolle-shaders/indirect-specular-denoising",
    "strolle-shaders/indirect-specular-resampling",
    "strolle-shaders/indirect-specular-resolving",
    "strolle-shaders/indirect-tracing",
    "strolle-shaders/reference-shading",
    "strolle-shaders/reference-tracing",
]

[patch."crates-io"]
# TODO https://github.com/gfx-rs/naga/issues/2373
naga = { git = "https://github.com/Patryk27/naga", branch = "v0.13.0-strolle" }
