[workspace]
resolver = "2"

members = [
    "bevy-strolle",
    "strolle",
    "strolle-models",
    "strolle-shader-builder",
    "strolle-shaders/denoising",
    "strolle-shaders/drawing",
    "strolle-shaders/raster",
    "strolle-shaders/ray-shading",
    "strolle-shaders/ray-tracing",
    "strolle-shaders/voxel-painting",
    "strolle-shaders/voxel-shading",
    "strolle-shaders/voxel-tracing",
]

exclude = [
    "utils/noise-visualizer",
]

[patch."https://github.com/EmbarkStudios/rust-gpu"]
# TODO bevy and rust-gpu use slightly different versions of glam at the moment
spirv-std = { git = "https://github.com/Patryk27/rust-gpu", branch = "strolle" }
