[package]
name = "strolle"
version = "0.1.0"
edition = "2021"

[dependencies]
# Workspace
strolle-models = { path = "../strolle-models" }

# Crates.io
bytemuck = "1"
log = "0.4"
rand = "0.8.5"
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu" }
wgpu = { version = "0.15", features = ["spirv"] }
